<?php

namespace ContainerCK7fcQo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ICAVMmRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iCAVMmR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iCAVMmR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.Iw7V3Qt', NULL, 'Cannot determine controller argument for "App\\Controller\\StoreController::product()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".'],
        ], [
            'request' => '?',
        ]);
    }
}
