<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSe2YRCF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSe2YRCF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSe2YRCF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSe2YRCF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSe2YRCF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Se2YRCF',
    'container.build_id' => '2363f778',
    'container.build_time' => 1608372128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSe2YRCF');
